DROP TABLE IF EXISTS ANAM_TIMED_EDGE;
CREATE TABLE ANAM_TIMED_EDGE (
  AME_T_OID            INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  AME_T_ENTRY_EDGE_ID  INT NOT NULL default '0',
  AME_T_DIRECT_EDGE_ID INT NOT NULL default '0',
  AME_T_EXIT_EDGE_ID   INT NOT NULL default '0',
  AME_T_CHILD_NODE     VARCHAR(64) NOT NULL default ' ',
  AME_T_PARENT_NODE    VARCHAR(64) NOT NULL default ' ',
  AME_T_STAGE          VARCHAR(64) NOT NULL default ' ',
  AME_T_HOPS           INT NOT NULL default '0',
  AME_T_SOURCE         VARCHAR(64) NOT NULL default ' '
) ENGINE=InnoDB DEFAULT CHARSET=latin1;		

