update ANA_PERSPECTIVE_AMBIT 
set PAM_COMMENTS = ''
where PAM_COMMENTS is null;

UPDATE ANA_ATTRIBUTION
SET ATR_COMMENTS = ''
where ATR_COMMENTS IS NULL;

DELETE FROM ANA_OBJECT WHERE
OBJ_OID IN (SELECT ATR_OID FROM ANA_ATTRIBUTION);

DELETE FROM ANA_OBJECT WHERE
OBJ_OID IN (SELECT ATR_OBJECT_FK FROM ANA_ATTRIBUTION);

-- ALTER TABLE ANA_OBJECT
-- ADD COLUMN OBJ_DESCRIPTION VARCHAR(255) NOT NULL DEFAULT '';
-- ALTER TABLE ANA_OBJECT
-- ADD COLUMN OBJ_TABLE VARCHAR(255) NOT NULL DEFAULT '';

UPDATE ANA_OBJECT 
SET OBJ_TABLE = "ANA_SOURCE",
OBJ_DESCRIPTION = "Grays Anatomy, 38th Edition",
OBJ_CREATION_DATETIME = "1999-04-08 15:11:27.0", 
OBJ_CREATOR_FK = 2
WHERE OBJ_OID = 3;
UPDATE ANA_OBJECT 
SET OBJ_TABLE = "ANA_SOURCE",
OBJ_DESCRIPTION = "The Anatomical Basis of Mouse Development",
OBJ_CREATION_DATETIME = "1999-04-08 15:11:27.0", 
OBJ_CREATOR_FK = 2
WHERE OBJ_OID = 4;
UPDATE ANA_OBJECT 
SET OBJ_TABLE = "ANA_SOURCE",
OBJ_DESCRIPTION = "Matthew H. Kaufman personal communication",
OBJ_CREATION_DATETIME = "1999-04-08 15:11:27.0", 
OBJ_CREATOR_FK = 2
WHERE OBJ_OID = 5;

UPDATE ANA_OBJECT 
SET OBJ_TABLE = "ANA_EDITOR",
OBJ_DESCRIPTION = "CIOF Translator",
OBJ_CREATION_DATETIME = "1999-04-08 15:11:27.0", 
OBJ_CREATOR_FK = 2 
WHERE OBJ_OID = 31614;
UPDATE ANA_OBJECT 
SET OBJ_TABLE = "ANA_EDITOR",
OBJ_DESCRIPTION = "Duncan Davidson",
OBJ_CREATION_DATETIME = "1999-04-08 15:11:27.0", 
OBJ_CREATOR_FK = 2 
WHERE OBJ_OID = 0;
UPDATE ANA_OBJECT 
SET OBJ_TABLE = "ANA_EDITOR",
OBJ_DESCRIPTION = "Jonathan Bard",
OBJ_CREATION_DATETIME = "1999-04-08 15:11:27.0", 
OBJ_CREATOR_FK = 2 
WHERE OBJ_OID = 1;
UPDATE ANA_OBJECT 
SET OBJ_TABLE = "ANA_EDITOR",
OBJ_DESCRIPTION = "sysadmin",
OBJ_CREATION_DATETIME = "1999-04-08 15:11:27.0", 
OBJ_CREATOR_FK = 2 
WHERE OBJ_OID = 2;

UPDATE ANA_STAGE
SET STG_SHORT_EXTRA_TEXT = ""
WHERE STG_OID = 30084;

UPDATE ANA_STAGE
SET STG_DESCRIPTION = "",
STG_PUBLIC_ID = "";

DELETE FROM ANA_OBJECT WHERE OBJ_DESCRIPTION = '';