CREATE TABLE ANA_TIMED_IDENTIFIER LIKE ANA_TIMED_NODE;

INSERT ANA_TIMED_IDENTIFIER SELECT * FROM ANA_TIMED_NODE;

ALTER TABLE ANA_TIMED_IDENTIFIER DROP KEY atn_public_id_index;
ALTER TABLE ANA_TIMED_IDENTIFIER DROP KEY ATN_AK2_INDEX;
ALTER TABLE ANA_TIMED_IDENTIFIER DROP KEY ATN_STAGE_FK;
ALTER TABLE ANA_TIMED_IDENTIFIER DROP KEY ATN_STAGE_MODIFIER_FK;

ALTER TABLE ANA_TIMED_IDENTIFIER DROP COLUMN ATN_NODE_FK;
ALTER TABLE ANA_TIMED_IDENTIFIER DROP COLUMN ATN_STAGE_FK;
ALTER TABLE ANA_TIMED_IDENTIFIER DROP COLUMN ATN_STAGE_MODIFIER_FK;
ALTER TABLE ANA_TIMED_IDENTIFIER DROP COLUMN ATN_PUBLIC_ID;
ALTER TABLE ANA_TIMED_IDENTIFIER DROP COLUMN ATN_DISPLAY_ID;

ALTER TABLE ANA_TIMED_IDENTIFIER CHANGE COLUMN ATN_OID ATI_OID int(10) unsigned NOT NULL;
ALTER TABLE ANA_TIMED_IDENTIFIER CHANGE COLUMN ATN_OLD_PUBLIC_ID ATI_OLD_PUBLIC_ID varchar(20) NOT NULL;
ALTER TABLE ANA_TIMED_IDENTIFIER CHANGE COLUMN ATN_OLD_DISPLAY_ID ATI_OLD_DISPLAY_ID varchar(20) NOT NULL;



