
UPDATE ANA_LOG
SET LOG_TABLE = 'ANA_ATTRIBUTION',
LOG_DATETIME = NOW()
WHERE SUBSTR(LOG_COLUMN_NAME,1,3) = 'ATR';

UPDATE ANA_LOG
SET LOG_TABLE = 'ANA_NODE',
LOG_DATETIME = NOW()
WHERE SUBSTR(LOG_COLUMN_NAME,1,3) = 'ANO';

UPDATE ANA_LOG
SET LOG_TABLE = 'ANA_TIMED_NODE',
LOG_DATETIME = NOW()
WHERE SUBSTR(LOG_COLUMN_NAME,1,3) = 'ATN';

UPDATE ANA_LOG
SET LOG_TABLE = 'ANA_RELATIONSHIP',
LOG_DATETIME = NOW()
WHERE SUBSTR(LOG_COLUMN_NAME,1,3) = 'REL';

UPDATE ANA_LOG
SET LOG_TABLE = 'ANA_SYNONYM',
LOG_DATETIME = NOW()
WHERE SUBSTR(LOG_COLUMN_NAME,1,3) = 'SYN';

UPDATE ANA_LOG
SET LOG_OLD_VALUE = ''
WHERE LOG_OLD_VALUE IS NULL;

UPDATE ANA_LOG
SET LOG_COMMENTS = ''
WHERE LOG_COMMENTS IS NULL;

SELECT * FROM ANA_LOG
WHERE LOG_OID IS NULL;

SELECT * FROM ANA_LOG
WHERE LOG_LOGGED_OID IS NULL;

SELECT * FROM ANA_LOG
WHERE LOG_VERSION_FK IS NULL;

SELECT * FROM ANA_LOG
WHERE LOG_COLUMN_NAME IS NULL;

SELECT * FROM ANA_LOG
WHERE LOG_OLD_VALUE IS NULL;

SELECT * FROM ANA_LOG
WHERE LOG_COMMENTS IS NULL;

SELECT * FROM ANA_LOG
WHERE LOG_DATETIME IS NULL;

SELECT * FROM ANA_LOG
WHERE LOG_TABLE IS NULL;
