-- Create ANA_NODE_PERSPECTIVE_LINK

-- 1. The 'Adult Kidney (GenePaint)' Perspective

-- Children of START Nodes
--  EXCLUDING STOP Nodes and their children
SELECT
'Adult Kidney (GenePaint)' AS NPL_PERSPECTIVE_FK,
AME_CHILD_NODE AS NPL_NODE_FK
FROM ANAM_EDGE
WHERE AME_PARENT_NODE IN (31638, 31627, 31639, 30107, 30106, 13125, 13133, 28804)
AND AME_CHILD_NODE NOT IN (SELECT
AME_PARENT_NODE
FROM ANAM_EDGE
WHERE AME_PARENT_NODE IN (27026, 26993, 27055, 30296, 31712, 27017))
UNION

-- START Nodes as well
SELECT
PAM_PERSPECTIVE_FK AS NPL_PERSPECTIVE_FK,
PAM_NODE_FK AS NPL_NODE_FK
FROM ANA_PERSPECTIVE_AMBIT
WHERE PAM_PERSPECTIVE_FK = 'Adult Kidney (GenePaint)'
AND PAM_IS_START = 1
UNION


-- 2. The 'Urogenital' Perspective

-- Children of START Nodes
SELECT
'Urogenital' AS NPL_PERSPECTIVE_FK,
AME_CHILD_NODE AS NPL_NODE_FK
FROM ANAM_EDGE
WHERE AME_PARENT_NODE IN (11673, 26962, 13306, 10381)
UNION

-- START Nodes as well
SELECT
PAM_PERSPECTIVE_FK AS NPL_PERSPECTIVE_FK,
PAM_NODE_FK AS NPL_NODE_FK
FROM ANA_PERSPECTIVE_AMBIT
WHERE PAM_PERSPECTIVE_FK = 'Urogenital'
AND PAM_IS_START = 1
UNION


-- 3. The 'Renal' Perspective

-- Children of START Nodes
SELECT
'Renal' AS NPL_PERSPECTIVE_FK,
AME_CHILD_NODE AS NPL_NODE_FK
FROM ANAM_EDGE
WHERE AME_PARENT_NODE IN (11673, 26962, 10381)
UNION

-- START Nodes as well
SELECT
PAM_PERSPECTIVE_FK AS NPL_PERSPECTIVE_FK,
PAM_NODE_FK AS NPL_NODE_FK
FROM ANA_PERSPECTIVE_AMBIT
WHERE PAM_PERSPECTIVE_FK = 'Renal'
AND PAM_IS_START = 1
UNION

-- 4. The 'Whole mouse' Perspective

-- Children of START Nodes
SELECT
'Whole mouse' AS NPL_PERSPECTIVE_FK,
AME_CHILD_NODE AS NPL_NODE_FK
FROM ANAM_EDGE
WHERE AME_PARENT_NODE IN (33)
UNION

-- START Nodes as well
SELECT
PAM_PERSPECTIVE_FK AS NPL_PERSPECTIVE_FK,
PAM_NODE_FK AS NPL_NODE_FK
FROM ANA_PERSPECTIVE_AMBIT
WHERE PAM_PERSPECTIVE_FK = 'Whole mouse'
AND PAM_IS_START = 1

ORDER BY NPL_PERSPECTIVE_FK, NPL_NODE_FK
