begin work;

-- =========================================================================================
-- script of table definition to store antonomical term relationships for different project
-- =========================================================================================

-- Create ANA_RELATIONSHIP_PROJECT
DROP TABLE IF EXISTS ANA_RELATIONSHIP_PROJECT;
CREATE TABLE ANA_RELATIONSHIP_PROJECT
(
  RLP_OID int(10) unsigned NOT NULL AUTO_INCREMENT,
  RLP_RELATIONSHIP_FK int(10) unsigned NOT NULL,
  RLP_PROJECT_FK char(30) NOT NULL,
  RLP_SEQUENCE int(10) unsigned default NULL,
    PRIMARY KEY (RLP_OID)
) 
  ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create ANA_PROJECT
DROP TABLE IF EXISTS ANA_PROJECT;
CREATE TABLE ANA_PROJECT 
(
  APJ_NAME char(30) NOT NULL,
    PRIMARY KEY (APJ_NAME)
) 
  ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- load the data into the tables
INSERT INTO ANA_PROJECT VALUES ('EMAP'), ('EMAGE'), ('EUREGENE'), ('EUREXPRESS'), ('GUDMAP');

INSERT into ANA_RELATIONSHIP_PROJECT (RLP_RELATIONSHIP_FK, RLP_SEQUENCE, RLP_PROJECT_FK)
SELECT REL_OID, REL_SEQUENCE, 'EMAP' FROM ANA_RELATIONSHIP ORDER BY REL_OID;

INSERT into ANA_RELATIONSHIP_PROJECT (RLP_RELATIONSHIP_FK, RLP_SEQUENCE, RLP_PROJECT_FK)
SELECT REL_OID, REL_SEQUENCE, 'GUDMAP' FROM ANA_RELATIONSHIP ORDER BY REL_OID;


-- Obliterate the SEQUENCE Numbers for EMAP, only GUDMAP is Ordered
UPDATE ANA_RELATIONSHIP_PROJECT
SET RLP_SEQUENCE = NULL 
WHERE RLP_PROJECT_FK = 'EMAP';


-- Add the Foreign Key Contraints
ALTER TABLE ANA_RELATIONSHIP_PROJECT
  ADD CONSTRAINT FK_RLP_RELATIONSHIP 
    FOREIGN KEY (RLP_RELATIONSHIP_FK) 
      REFERENCES ANA_RELATIONSHIP (REL_OID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ANA_RELATIONSHIP_PROJECT
  ADD CONSTRAINT FK_RLP_PROJECT 
    FOREIGN KEY (RLP_PROJECT_FK) 
      REFERENCES ANA_PROJECT (APJ_NAME) ON DELETE NO ACTION ON UPDATE NO ACTION;

commit work;