SELECT 
ANAV_STAGE AS STAGE,
CAST(ANAV_OID_1 AS CHAR) AS ROOT_OID, 
ANAV_NAME_1 AS ROOT_NAME, 
ANAV_DESC_1 AS ROOT_DESC, 
CAST(ANAV_OID_2 AS CHAR) AS CHILD_OID, 
'LEAF' AS CHILD_ID, 
ANAV_NAME_2 AS CHILD_NAME, 
ANAV_DESC_2 AS CHILD_DESC, 
'No Children' AS GRAND_CHILD_ID, 
'No Children' AS GRAND_CHILD_NAME, 
'No Children' AS GRAND_CHILD_DESC
FROM ANAV_TIMED_LEAF_RELATION
WHERE ANAV_NAME_1 = 'EMAP:27551'
AND ANAV_STAGE = 'TS27'
UNION
SELECT 
STG_NAME AS STAGE,
ANAV_ID_1, 
ANAV_NAME_1, 
ANAV_DESC_1, 
CAST(ANAV_OID_2 AS CHAR), 
ANAV_ID_2, 
ANAV_NAME_2, 
ANAV_DESC_2, 
ANAV_ID_3, 
ANAV_NAME_3, 
ANAV_DESC_3
FROM ANAV_TIMED_GRAND_RELATION
JOIN ANA_STAGE ON STG_OID = ANAV_STAGE
WHERE ANAV_NAME_1 = 'EMAP:27551'
AND STG_NAME = 'TS27'
ORDER BY CHILD_NAME
