SELECT CONCAT("UPDATE ANA_OBJECT SET OBJ_TABLE = \"ANA_NODE\", OBJ_DESCRIPTION = \"", ANO_PUBLIC_ID, " (", ANO_COMPONENT_NAME, ") FROM: ", c.STG_NAME, " TO: ", d.STG_NAME, "\", OBJ_CREATOR_FK = 2 WHERE OBJ_OID = ", ANO_OID, ";") AS NODE_STRING
FROM ANA_NODE
JOIN ANAV_STAGE_RANGE a ON ANO_OID = a.ANAV_NODE_FK
JOIN ANA_STAGE c ON c.STG_SEQUENCE = a.ANAV_STAGE_MIN
JOIN ANA_STAGE d ON d.STG_SEQUENCE  = a.ANAV_STAGE_MAX;