SELECT CONCAT("UPDATE ANA_OBJECT SET OBJ_TABLE = \"ANA_RELATIONSHIP\", OBJ_DESCRIPTION = \"", a.ANO_PUBLIC_ID, "(", a.ANO_COMPONENT_NAME, ") ", REL_RELATIONSHIP_TYPE_FK, " ", b.ANO_PUBLIC_ID, " (", b.ANO_COMPONENT_NAME, ")\", OBJ_CREATOR_FK = 2 WHERE OBJ_OID = ", REL_OID, ";") 
AS RELATIONSHIP_STRING
FROM ANA_RELATIONSHIP
JOIN ANA_NODE a ON REL_CHILD_FK = a.ANO_OID
JOIN ANA_NODE b ON REL_PARENT_FK = b.ANO_OID;