SELECT CONCAT("UPDATE ANA_OBJECT SET OBJ_TABLE = \"ANA_STAGE\", OBJ_DESCRIPTION = \"", STG_NAME, " (", STG_SHORT_EXTRA_TEXT, ") (", "ORDER: ", STG_SEQUENCE, ")\", OBJ_CREATION_DATETIME = \"1999-04-08 15:11:27.0\", OBJ_CREATOR_FK = 2 WHERE OBJ_OID = ", STG_OID, ";")
AS STAGE_STRING
FROM ANA_STAGE;