SELECT CONCAT("UPDATE ANA_OBJECT SET OBJ_TABLE = \"ANA_SYNONYM\", OBJ_DESCRIPTION = \"(", a.ANO_PUBLIC_ID, " : ", a.ANO_COMPONENT_NAME, ") SYN: ", SYN_SYNONYM, "\", OBJ_CREATOR_FK = 2 WHERE OBJ_OID = ", SYN_OID, ";")
AS SYNONYM_STRING
FROM ANA_SYNONYM
JOIN ANA_NODE a ON SYN_OBJECT_FK = a.ANO_OID;