SELECT CONCAT("UPDATE ANA_OBJECT SET OBJ_TABLE = \"ANA_PERSPECTIVE_AMBIT\", OBJ_DESCRIPTION = \"", PAM_PERSPECTIVE_FK, ": ", a.ANO_PUBLIC_ID, "(", a.ANO_COMPONENT_NAME, ") ", IF ( PAM_IS_START = 1, "(START NODE)", ""), IF ( PAM_IS_STOP = 1, "(STOP NODE)", ""), "\", OBJ_CREATION_DATETIME = \"2002-04-09 12:19:32\", OBJ_CREATOR_FK = 2 WHERE OBJ_OID = ", PAM_OID, ";")
AS PERSPECTIVE_STRING
FROM ANA_PERSPECTIVE_AMBIT
JOIN ANA_NODE a ON PAM_NODE_FK = a.ANO_OID;