SELECT CONCAT("UPDATE ANA_OBJECT SET OBJ_TABLE = \"ANA_SYNONYM\", OBJ_DESCRIPTION = \"(", a.ANO_PUBLIC_ID, " : ", a.ANO_COMPONENT_NAME, ") Syn: ", SYN_SYNONYM, "\", OBJ_CREATOR_FK = 2 WHERE OBJ_OID = ", SYN_OID, ";")
AS SYNONYM_STRING
FROM ANA_SYNONYM
JOIN ANA_NODE a ON SYN_OBJECT_FK = a.ANO_OID

SELECT CONCAT("UPDATE ANA_OBJECT SET OBJ_TABLE = \"ANA_RELATIONSHIP\", OBJ_DESCRIPTION = \"", a.ANO_PUBLIC_ID, "(", a.ANO_COMPONENT_NAME, ") ", REL_RELATIONSHIP_TYPE_FK, " ", b.ANO_PUBLIC_ID, " (", b.ANO_COMPONENT_NAME, ")\", OBJ_CREATOR_FK = 2 WHERE OBJ_OID = ", REL_OID, ";") 
AS RELATIONSHIP_STRING
FROM ANA_RELATIONSHIP
JOIN ANA_NODE a ON REL_CHILD_FK = a.ANO_OID
JOIN ANA_NODE b ON REL_PARENT_FK = b.ANO_OID

SELECT CONCAT("UPDATE ANA_OBJECT SET OBJ_TABLE = \"ANA_TIMED_NODE\", OBJ_DESCRIPTION = \"", ATN_PUBLIC_ID, " is ", a.ANO_PUBLIC_ID, " (", a.ANO_COMPONENT_NAME, ") at ", b.STG_NAME, "\", OBJ_CREATOR_FK = 2 WHERE OBJ_OID = ", ATN_OID, ";") 
AS TIMED_NODE_STRING
FROM ANA_TIMED_NODE
JOIN ANA_NODE a ON ATN_NODE_FK = a.ANO_OID
JOIN ANA_STAGE b ON ATN_STAGE_FK = b.STG_OID

SELECT CONCAT("UPDATE ANA_OBJECT SET OBJ_TABLE = \"ANA_NODE\", OBJ_DESCRIPTION = \"", ANO_PUBLIC_ID, " (", ANO_COMPONENT_NAME, ") FROM: ", c.STG_NAME, " TO: ", d.STG_NAME, "\", OBJ_CREATOR_FK = 2 WHERE OBJ_OID = ", ANO_OID, ";") AS NODE_STRING
FROM ANA_NODE
JOIN ANAV_STAGE_RANGE a ON ANO_OID = a.ANAV_NODE_FK
JOIN ANA_STAGE c ON c.STG_OID = a.ANAV_STAGE_MIN
JOIN ANA_STAGE d ON d.STG_OID = a.ANAV_STAGE_MAX

SELECT CONCAT("UPDATE ANA_OBJECT SET OBJ_TABLE = \"ANA_STAGE\", OBJ_DESCRIPTION = \"", STG_NAME, " (", STG_SHORT_EXTRA_TEXT, ") (", "Order: ", STG_SEQUENCE, ")\", OBJ_CREATION_DATETIME = \"1999-04-08 15:11:27.0\", OBJ_CREATOR_FK = 2 WHERE OBJ_OID = ", STG_OID, ";")
AS STAGE_STRING
FROM ANA_STAGE

SELECT CONCAT("UPDATE ANA_OBJECT SET OBJ_TABLE = \"ANA_PERPECTIVE_AMBIT\", OBJ_DESCRIPTION = \"", PAM_PERSPECTIVE_FK, ": ", a.ANO_PUBLIC_ID, "(", a.ANO_COMPONENT_NAME, ") ", IF ( PAM_IS_START = 1, "(START NODE)", ""), IF ( PAM_IS_STOP = 1, "(STOP NODE)", ""), "\", OBJ_CREATION_DATETIME = \"2002-04-09 12:19:32\", OBJ_CREATOR_FK = 2 WHERE OBJ_OID = ", PAM_OID, ";")
AS PERSPECTIVE_STRING
FROM ANA_PERSPECTIVE_AMBIT
JOIN ANA_NODE a ON PAM_NODE_FK = a.ANO_OID

SELECT CONCAT("UPDATE ANA_OBJECT SET OBJ_TABLE = \"ANA_VERSION\", OBJ_DESCRIPTION = \"VERSION00", VER_NUMBER, "\", OBJ_CREATION_DATETIME = ", VER_DATE, "\", OBJ_CREATOR_FK = 2 WHERE OBJ_OID = ", VER_OID, ";")
AS VERSION_STRING
FROM ANA_VERSION


SELECT ATR_OID, ATR_SOURCE_FK, ATR_EVIDENCE_FK, ATR_OBJECT_FK, OBJ_OID, OBJ_TABLE, OBJ_DESCRIPTION 
FROM ANA_ATTRIBUTION
join ANA_OBJECT on ATR_OBJECT_FK = OBJ_OID

SELECT * FROM ANA_OBJECT WHERE
OBJ_OID IN (SELECT ATR_OID FROM ANA_ATTRIBUTION);

DELETE FROM ANA_OBJECT WHERE
OBJ_OID IN (SELECT ATR_OID FROM ANA_ATTRIBUTION);

SELECT * FROM ANA_OBJECT WHERE
OBJ_OID IN (SELECT ATR_OBJECT_FK FROM ANA_ATTRIBUTION);

DELETE FROM ANA_OBJECT WHERE
OBJ_OID IN (SELECT ATR_OBJECT_FK FROM ANA_ATTRIBUTION);


SELECT * FROM ANA_OBJECT WHERE OBJ_DESCRIPTION = ''
