SELECT CONCAT("CALL ANASP_ADD_EDGE(",
REL_CHILD_FK,  ", ",
a.ANV_STAGE_MIN, ", ",
a.ANV_STAGE_MAX, ", ",
REL_PARENT_FK, ", ",
b.ANV_STAGE_MIN, ", ",
b.ANV_STAGE_MAX, ", ",
"\"BUILD EDGES by MNW on 2011-12-08\");") as RELATIONSHIP_STRING
FROM ANA_RELATIONSHIP
JOIN ANAV_STAGE_RANGE a ON REL_CHILD_FK = a.ANV_NODE_FK
JOIN ANAV_STAGE_RANGE b ON REL_PARENT_FK = b.ANV_NODE_FK

