insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30085, 3575, NULL, "part-of", 31266);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30086, 3575, NULL, "part-of", 31267);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30087, 6773, NULL, "part-of", 31268);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30088, 7733, NULL, "part-of", 31269);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30089, 8527, NULL, "part-of", 31270);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30090, 8593, NULL, "part-of", 31271);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30091, 8660, NULL, "part-of", 31272);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30092, 8732, NULL, "part-of", 31273);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30093, 8794, NULL, "part-of", 31274);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30094, 8866, NULL, "part-of", 31275);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30095, 8976, NULL, "part-of", 31276);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30096, 9051, NULL, "part-of", 31277);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30097, 9185, NULL, "part-of", 31278);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30098, 9257, NULL, "part-of", 31279);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30099, 9329, NULL, "part-of", 31280);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30100, 10336, NULL, "part-of", 31281);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30101, 10450, NULL, "part-of", 31282);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30102, 30101, NULL, "part-of", 31283);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30103, 30101, NULL, "part-of", 31284);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30104, 10450, NULL, "part-of", 31285);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30105, 10381, NULL, "part-of", 31286);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30106, 11719, NULL, "part-of", 31287);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12074, 30106, NULL, "part-of", 31288);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12081, 30106, NULL, "part-of", 31289);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12088, 30106, NULL, "part-of", 31290);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30107, 11719, NULL, "part-of", 31291);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30108, 30107, NULL, "part-of", 31292);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30109, 30107, NULL, "part-of", 31293);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30110, 12023, NULL, "part-of", 31294);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30111, 12242, NULL, "part-of", 31295);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30112, 12272, NULL, "part-of", 31296);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30113, 12467, NULL, "part-of", 31297);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30114, 12505, NULL, "part-of", 31298);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12515, 12505, NULL, "part-of", 31299);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30115, 12515, NULL, "part-of", 31300);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30116, 12515, NULL, "part-of", 31301);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30117, 12551, NULL, "part-of", 31302);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30118, 12734, NULL, "part-of", 31303);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30119, 30118, NULL, "part-of", 31304);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30120, 30118, NULL, "part-of", 31305);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30121, 12734, NULL, "part-of", 31306);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30122, 30121, NULL, "part-of", 31307);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30123, 30121, NULL, "part-of", 31308);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30124, 12734, NULL, "part-of", 31309);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30125, 30124, NULL, "part-of", 31310);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30126, 30124, NULL, "part-of", 31311);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30127, 30124, NULL, "part-of", 31312);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30128, 30124, NULL, "part-of", 31313);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30129, 11673, NULL, "part-of", 31314);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12996, 30129, NULL, "part-of", 31315);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12999, 30129, NULL, "part-of", 31316);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30130, 13026, NULL, "part-of", 31317);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 13060, 30129, NULL, "part-of", 31318);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 13098, 30129, NULL, "part-of", 31319);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 13108, 30129, NULL, "part-of", 31320);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 13112, 30129, NULL, "part-of", 31321);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30131, 30129, NULL, "part-of", 31322);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30132, 12832, NULL, "part-of", 31323);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30133, 12853, NULL, "part-of", 31324);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30134, 12874, NULL, "part-of", 31325);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30135, 12902, NULL, "part-of", 31326);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30136, 12930, NULL, "part-of", 31327);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30137, 12794, NULL, "part-of", 31328);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30138, 30137, NULL, "part-of", 31329);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30139, 30137, NULL, "part-of", 31330);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30140, 30137, NULL, "part-of", 31331);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30141, 13155, NULL, "part-of", 31332);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30142, 30141, NULL, "part-of", 31333);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30143, 30141, NULL, "part-of", 31334);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30144, 30141, NULL, "part-of", 31335);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30145, 13155, NULL, "part-of", 31336);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30146, 30145, NULL, "part-of", 31337);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30147, 30145, NULL, "part-of", 31338);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30148, 30145, NULL, "part-of", 31339);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30149, 13240, NULL, "part-of", 31340);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30150, 30149, NULL, "part-of", 31341);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30151, 30149, NULL, "part-of", 31342);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30152, 30149, NULL, "part-of", 31343);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30153, 30149, NULL, "part-of", 31344);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30154, 30149, NULL, "part-of", 31345);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30155, 11673, NULL, "part-of", 31346);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30156, 11673, NULL, "part-of", 31347);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30157, 30156, NULL, "part-of", 31348);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30158, 30157, NULL, "part-of", 31349);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30159, 30157, NULL, "part-of", 31350);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30160, 30157, NULL, "part-of", 31351);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30161, 30156, NULL, "part-of", 31352);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30162, 30161, NULL, "part-of", 31353);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30163, 30161, NULL, "part-of", 31354);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30164, 13316, NULL, "part-of", 31355);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30165, 13316, NULL, "part-of", 31356);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30166, 28808, NULL, "part-of", 31357);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30167, 28808, NULL, "part-of", 31358);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30168, 28812, NULL, "part-of", 31359);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30169, 13391, NULL, "part-of", 31360);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30170, 13391, NULL, "part-of", 31361);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30171, 30170, NULL, "part-of", 31362);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30172, 30170, NULL, "part-of", 31363);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30173, 13391, NULL, "part-of", 31364);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30174, 30173, NULL, "part-of", 31365);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30175, 30173, NULL, "part-of", 31366);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30176, 30175, NULL, "part-of", 31367);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30177, 30175, NULL, "part-of", 31368);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30178, 30173, NULL, "part-of", 31369);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30179, 30173, NULL, "part-of", 31370);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30180, 13391, NULL, "part-of", 31371);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30181, 30180, NULL, "part-of", 31372);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30182, 30180, NULL, "part-of", 31373);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30183, 30182, NULL, "part-of", 31374);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30184, 30182, NULL, "part-of", 31375);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30185, 30180, NULL, "part-of", 31376);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30186, 30180, NULL, "part-of", 31377);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30187, 13391, NULL, "part-of", 31378);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30188, 13508, NULL, "part-of", 31379);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30189, 13508, NULL, "part-of", 31380);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30190, 13521, NULL, "part-of", 31381);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30191, 13521, NULL, "part-of", 31382);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30192, 13525, NULL, "part-of", 31383);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30193, 13525, NULL, "part-of", 31384);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30194, 13515, NULL, "part-of", 31385);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30195, 13515, NULL, "part-of", 31386);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30196, 30195, NULL, "part-of", 31387);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30197, 30195, NULL, "part-of", 31388);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30198, 30195, NULL, "part-of", 31389);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30199, 13515, NULL, "part-of", 31390);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30200, 30199, NULL, "part-of", 31391);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30201, 30199, NULL, "part-of", 31392);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30202, 13515, NULL, "part-of", 31393);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30203, 30202, NULL, "part-of", 31394);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30204, 30202, NULL, "part-of", 31395);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30205, 30202, NULL, "part-of", 31396);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30206, 28840, NULL, "part-of", 31397);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30207, 30206, NULL, "part-of", 31398);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30208, 30206, NULL, "part-of", 31399);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30209, 13534, NULL, "part-of", 31400);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30210, 13539, NULL, "part-of", 31401);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30211, 13545, NULL, "part-of", 31402);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30212, 13606, NULL, "part-of", 31403);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30213, 30212, NULL, "part-of", 31404);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30214, 30212, NULL, "part-of", 31405);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30215, 13606, NULL, "part-of", 31406);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30216, 13630, NULL, "part-of", 31407);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30217, 13630, NULL, "part-of", 31408);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30218, 28861, NULL, "part-of", 31409);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30219, 13350, NULL, "part-of", 31410);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30220, 30219, NULL, "part-of", 31411);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30221, 30219, NULL, "part-of", 31412);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30222, 13350, NULL, "part-of", 31413);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30223, 30222, NULL, "part-of", 31414);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30224, 30223, NULL, "part-of", 31415);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30225, 30223, NULL, "part-of", 31416);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30226, 30223, NULL, "part-of", 31417);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30227, 30222, NULL, "part-of", 31418);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30228, 30227, NULL, "part-of", 31419);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30229, 30227, NULL, "part-of", 31420);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30230, 30222, NULL, "part-of", 31421);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30231, 13350, NULL, "part-of", 31422);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30232, 30231, NULL, "part-of", 31423);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30233, 30231, NULL, "part-of", 31424);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30234, 30231, NULL, "part-of", 31425);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30235, 30231, NULL, "part-of", 31426);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30236, 28879, NULL, "part-of", 31427);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30237, 28886, NULL, "part-of", 31428);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30238, 28886, NULL, "part-of", 31429);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30239, 13686, NULL, "part-of", 31430);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30240, 13686, NULL, "part-of", 31431);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30241, 30240, NULL, "part-of", 31432);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30242, 30240, NULL, "part-of", 31433);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30243, 30240, NULL, "part-of", 31434);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30244, 13677, NULL, "part-of", 31435);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30245, 28918, NULL, "part-of", 31436);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30246, 28918, NULL, "part-of", 31437);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30247, 13828, NULL, "part-of", 31438);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30248, 13828, NULL, "part-of", 31439);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30249, 13860, NULL, "part-of", 31440);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30250, 13860, NULL, "part-of", 31441);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30251, 13865, NULL, "part-of", 31442);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30252, 13865, NULL, "part-of", 31443);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30253, 13865, NULL, "part-of", 31444);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30254, 13870, NULL, "part-of", 31445);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30255, 13870, NULL, "part-of", 31446);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30256, 13854, NULL, "part-of", 31447);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30257, 13929, NULL, "part-of", 31448);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30258, 13958, NULL, "part-of", 31449);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30259, 28941, NULL, "part-of", 31450);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30260, 30259, NULL, "part-of", 31451);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30261, 30259, NULL, "part-of", 31452);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30262, 28941, NULL, "part-of", 31453);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30263, 28939, NULL, "part-of", 31454);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30264, 28939, NULL, "part-of", 31455);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30265, 30264, NULL, "part-of", 31456);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30266, 30264, NULL, "part-of", 31457);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30267, 28954, NULL, "part-of", 31458);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30268, 28965, NULL, "part-of", 31459);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30269, 28965, NULL, "part-of", 31460);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30270, 28966, NULL, "part-of", 31461);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30271, 28966, NULL, "part-of", 31462);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30272, 28966, NULL, "part-of", 31463);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30273, 28966, NULL, "part-of", 31464);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30274, 28979, NULL, "part-of", 31465);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28981, 30274, NULL, "part-of", 31466);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28982, 30274, NULL, "part-of", 31467);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30275, 30274, NULL, "part-of", 31468);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30276, 28983, NULL, "part-of", 31469);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30277, 13677, NULL, "part-of", 31470);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30278, 13677, NULL, "part-of", 31471);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30279, 30278, NULL, "part-of", 31472);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30280, 30278, NULL, "part-of", 31473);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30281, 13970, NULL, "part-of", 31474);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30282, 13970, NULL, "part-of", 31475);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30283, 30282, NULL, "part-of", 31476);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30284, 30282, NULL, "part-of", 31477);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30285, 14694, NULL, "part-of", 31478);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30286, 17876, NULL, "part-of", 31479);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30287, 30286, NULL, "part-of", 31480);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30288, 30286, NULL, "part-of", 31481);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30289, 30286, NULL, "part-of", 31482);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 18002, 30286, NULL, "part-of", 31483);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30290, 20866, NULL, "part-of", 31484);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30291, 20866, NULL, "part-of", 31485);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30292, 11719, NULL, "part-of", 31486);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 11922, 30292, NULL, "part-of", 31487);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 11928, 30292, NULL, "part-of", 31488);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 11940, 30292, NULL, "part-of", 31489);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 11965, 30292, NULL, "part-of", 31490);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 11985, 30292, NULL, "part-of", 31491);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12108, 30292, NULL, "part-of", 31492);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12117, 30292, NULL, "part-of", 31493);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12138, 30292, NULL, "part-of", 31494);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12191, 30292, NULL, "part-of", 31495);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12235, 30292, NULL, "part-of", 31496);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12310, 30292, NULL, "part-of", 31497);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12392, 30292, NULL, "part-of", 31498);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 11982, 26973, NULL, "part-of", 31499);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12640, 27007, NULL, "part-of", 31500);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12676, 27007, NULL, "part-of", 31501);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30114, 27035, NULL, "part-of", 31502);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30244, 27065, NULL, "part-of", 31503);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30293, 28966, NULL, "part-of", 31504);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28974, 30293, NULL, "part-of", 31505);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28978, 30293, NULL, "part-of", 31506);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28970, 30293, NULL, "part-of", 31507);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30294, 28966, NULL, "part-of", 31508);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28972, 30294, NULL, "part-of", 31509);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28976, 30294, NULL, "part-of", 31510);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28968, 30294, NULL, "part-of", 31511);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30295, 28966, NULL, "part-of", 31512);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28973, 30295, NULL, "part-of", 31513);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28977, 30295, NULL, "part-of", 31514);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28969, 30295, NULL, "part-of", 31515);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30296, 12094, NULL, "part-of", 31516);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12437, 30296, NULL, "part-of", 31517);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12449, 30296, NULL, "part-of", 31518);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 12372, 30296, NULL, "part-of", 31519);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30297, 13677, NULL, "part-of", 31520);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 13686, 30297, NULL, "part-of", 31521);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 13854, 30297, NULL, "part-of", 31522);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 13958, 30297, NULL, "part-of", 31523);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28965, 30297, NULL, "part-of", 31524);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30278, 30297, NULL, "part-of", 31525);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30298, 13350, NULL, "part-of", 31526);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 13508, 30298, NULL, "part-of", 31527);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 13515, 30298, NULL, "part-of", 31528);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30219, 30298, NULL, "part-of", 31529);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30222, 30298, NULL, "part-of", 31530);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30231, 30298, NULL, "part-of", 31531);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30299, 13545, NULL, "part-of", 31532);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28847, 30299, NULL, "part-of", 31533);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28852, 30299, NULL, "part-of", 31534);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30300, 13545, NULL, "part-of", 31535);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28850, 30300, NULL, "part-of", 31536);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28855, 30300, NULL, "part-of", 31537);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30301, 13545, NULL, "part-of", 31538);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28856, 30301, NULL, "part-of", 31539);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 28851, 30301, NULL, "part-of", 31540);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30302, 13391, NULL, "part-of", 31541);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30187, 30302, NULL, "part-of", 31542);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30166, 30302, NULL, "part-of", 31543);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 27007, 26945, NULL, "part-of", 31544);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30317, 3245, NULL, "derives-from", 31545);show warnings;

insert into ANA_RELATIONSHIP    ( REL_CHILD_FK, REL_PARENT_FK, REL_SEQUENCE, REL_RELATIONSHIP_TYPE_FK, REL_OID)  values    ( 30326, 3245, NULL, "derives-from", 31546);show warnings;

