SELECT CONCAT("CALL ANASP_ADD_EDGE(",
REL_CHILD_FK,  ", ",
a.ANAV_STAGE_MIN, ", ",
a.ANAV_STAGE_MAX, ", ",
REL_PARENT_FK, ", ",
b.ANAV_STAGE_MIN, ", ",
b.ANAV_STAGE_MAX, ", ",
"\"BUILD EDGES by MNW on 2011-12-08\");")
FROM ANA_RELATIONSHIP
JOIN ANAV_STAGE_RANGE a ON REL_CHILD_FK = a.ANAV_NODE_FK
JOIN ANAV_STAGE_RANGE b ON REL_PARENT_FK = b.ANAV_NODE_FK;