SELECT CONCAT("CALL ANASP_ADD_TIMED_EDGE(",
ANAV_REL_CHILD_FK,  ", ",
ANAV_REL_PARENT_FK, ", ",
ANAV_REL_STAGE, ", ",
"\"BUILD TIMED_EDGES by MNW on 2012-07-16\");") AS '-- COMMENT'
FROM ANAV_RELATIONSHIP_TIMED;