DROP TABLE IF EXISTS ANA_OBO_COMPONENT_ALTERNATIVE;
CREATE TABLE ANA_OBO_COMPONENT_ALTERNATIVE (
  ACA_OID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  ACA_OBO_ID varchar(25) NOT NULL,
  ACA_OBO_ALT_ID varchar(25) NOT NULL,
  PRIMARY KEY (ACA_OID),
  KEY ACA_IDX1 (ACA_OBO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;