DROP TABLE IF EXISTS ANA_OBO_COMPONENT_ORDER;
CREATE TABLE ANA_OBO_COMPONENT_ORDER (
  ACO_OID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  ACO_OBO_CHILD varchar(25) NOT NULL,
  ACO_OBO_PARENT varchar(25) NOT NULL,
  ACO_OBO_TYPE varchar(25) NOT NULL,
  ACO_OBO_ALPHA_ORDER int(10) unsigned DEFAULT NULL,
  ACO_OBO_SPECIAL_ORDER int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (ACO_OID),
  KEY ACO_IDX1 (ACO_OBO_CHILD),
  KEY ACO_IDX2 (ACO_OBO_PARENT)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;