--private String name;
--private String id;
--private String dbID;
--private String newid;
--private String namespace;
--private Boolean group;
--private String start;
--private String end;
--private Integer present;
--private String statusChange; //"UNCHANGED"|"NEW"|"CHANGED"|"DELETED"
--private String statusRule;   //"UNCHECKED"|"PASSED"|"FAILED"

DROP TABLE IF EXISTS ANA_OBO_COMPONENT;
CREATE TABLE ANA_OBO_COMPONENT (
    AOC_OID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    AOC_NAME VARCHAR(255) NOT NULL,
    AOC_OBO_ID VARCHAR(25) NOT NULL,
    AOC_DB_ID VARCHAR(25) NOT NULL,
    AOC_NEW_ID VARCHAR(25) NOT NULL,
    AOC_NAMESPACE VARCHAR(50) NOT NULL,
    AOC_GROUP TINYINT(1) NOT NULL,
    AOC_START VARCHAR(10) NOT NULL,
    AOC_END VARCHAR(10) NOT NULL,
    AOC_PRESENT VARCHAR(10) NOT NULL,
    AOC_STATUS_CHANGE VARCHAR(10) NOT NULL COMMENT "UNCHANGED NEW CHANGED DELETED",
    AOC_STATUS_RULE VARCHAR(10) NOT NULL COMMENT "UNCHECKED PASSED FAILED",
    INDEX AOC_IDX1 (AOC_OBO_ID),
    PRIMARY KEY (AOC_OID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
