SELECT 
  CAST(AME_OID_1 AS CHAR) AS ROOT_OID, 
  AME_NAME_1 AS ROOT_NAME, 
  AME_DESC_1 AS ROOT_DESC, 
  b.AME_STAGE_MIN AS ROOT_MIN_STAGE,
  b.AME_STAGE_MAX AS ROOT_MAX_STAGE, 
  CAST(AME_OID_2 AS CHAR) AS CHILD_OID, 
  'LEAF' AS CHILD_ID, 
  AME_NAME_2 AS CHILD_NAME, 
  AME_DESC_2 AS CHILD_DESC, 
  c.AME_STAGE_MIN AS CHILD_MIN_STAGE,
  c.AME_STAGE_MIN AS CHILD_MAX_STAGE, 
  'No Children' AS GRAND_CHILD_ID, 
  'No Children' AS GRAND_CHILD_NAME, 
  'No Children' AS GRAND_CHILD_DESC,
  'No Children' AS GRAND_CHILD_MIN_STAGE,
  'No Children' AS GRAND_CHILD_MAX_STAGE
FROM ANAM_LEAF_RELATION a
JOIN ANAM_STAGE_RANGE b ON AME_OID_1 = b.AME_NODE_FK
JOIN ANAM_STAGE_RANGE c ON AME_OID_2 = c.AME_NODE_FK 
WHERE AME_DESC_1 = 'mouse'

SELECT AME_ID_1, 
AME_NAME_1, 
AME_DESC_1, 
c.AME_STAGE_MIN AS ROOT_MIN_STAGE,
c.AME_STAGE_MAX AS ROOT_MAX_STAGE, 
CAST(AME_OID_2 AS CHAR), 
AME_ID_2, 
AME_NAME_2, 
AME_DESC_2, 
d.AME_STAGE_MIN AS CHILD_MIN_STAGE,
d.AME_STAGE_MAX AS CHILD_MAX_STAGE, 
AME_ID_3, 
AME_NAME_3, 
AME_DESC_3,
e.AME_STAGE_MIN AS GRAND_CHILD_MIN_STAGE,
e.AME_STAGE_MAX AS GRAND_CHILD_MAX_STAGE
FROM AME_GRAND_RELATION
JOIN AME_STAGE_RANGE c ON AME_ID_1 = c.AME_NODE_FK
JOIN AME_STAGE_RANGE d ON AME_ID_2 = d.AME_NODE_FK 
JOIN AME_STAGE_RANGE e ON AME_ID_3 = e.AME_NODE_FK
WHERE AME_DESC_1 = 'mouse'


SELECT *
FROM anav_leaf_relation a
WHERE AME_PARENT_DESC_1 = 'mouse'
order by AME_PARENT_STG_MIN_1, AME_PARENT_STG_MAX_1


SELECT CAST(AME_OID_1 AS CHAR) AS ROOT_OID, AME_NAME_1 AS ROOT_NAME, AME_DESC_1 AS ROOT_DESC, CAST(AME_OID_2 AS CHAR) AS CHILD_OID, 'LEAF' AS CHILD_ID, AME_NAME_2 AS CHILD_NAME, AME_DESC_2 AS CHILD_DESC, 'No Children' AS GRAND_CHILD_ID, 'No Children' AS GRAND_CHILD_NAME, 'No Children' AS GRAND_CHILD_DESC
FROM anav_leaf_relation a
WHERE AME_DESC_1 = 'mouse'
UNION
SELECT AME_ID_1, AME_NAME_1, AME_DESC_1, CAST(AME_OID_2 AS CHAR), AME_ID_2, AME_NAME_2, AME_DESC_2, AME_ID_3, AME_NAME_3, AME_DESC_3
FROM AME_GRAND_RELATION
WHERE AME_DESC_1 = 'mouse'


SELECT
  ANV_OID, 
  ANV_PARENT_ID,
  ANV_PARENT_NAME,
  ANV_PARENT_DESC,
  ANV_CHILD_ID, 
  ANV_CHILD_NAME, 
  ANV_CHILD_DESC, 
  ANV_HOPS
FROM AME_RELATION
WHERE ANV_PARENT_DESC = 'mouse'
AND ANV_HOPS = 0
ORDER BY ANV_PARENT_NAME, ANV_CHILD_NAME

SELECT
  ANV_OID, 
  ANV_PARENT_ID,
  ANV_PARENT_NAME,
  ANV_PARENT_DESC,
  ANV_CHILD_ID, 
  ANV_CHILD_NAME, 
  ANV_CHILD_DESC, 
  ANV_HOPS
FROM AME_RELATION
WHERE ANV_PARENT_ID in (SELECT
  ANV_CHILD_ID 
FROM AME_RELATION
WHERE ANV_PARENT_DESC = 'mouse'
AND ANV_HOPS = 1)


SELECT
  ANV_CHILD_ID 
FROM AME_RELATION
WHERE ANV_PARENT_DESC = 'mouse'
AND ANV_HOPS = 1

SELECT
  a.ANV_PARENT_ID AS P_ID_1,
  a.ANV_PARENT_NAME AS P_NAME_1,
  a.ANV_PARENT_DESC AS P_DESC_1,
  a.ANV_HOPS AS HOPS_1,
  b.ANV_PARENT_ID AS P_ID_2,
  b.ANV_PARENT_NAME AS P_NAME_2,
  b.ANV_PARENT_DESC AS P_DESC_2,
  b.ANV_CHILD_ID AS C_ID_2,
  b.ANV_CHILD_NAME AS C_NAME_2,
  b.ANV_CHILD_DESC AS C_DESC_2,
  b.ANV_HOPS AS HOPS_2
FROM AME_RELATION a
JOIN AME_RELATION b ON a.ANV_CHILD_ID = b.ANV_PARENT_ID
WHERE a.ANV_PARENT_DESC = 'mouse'
AND a.ANV_HOPS = 0 AND b.ANV_HOPS = 0

SELECT
  a.ANV_PARENT_ID AS P_ID_1,
  a.ANV_PARENT_NAME AS P_NAME_1,
  a.ANV_PARENT_DESC AS P_DESC_1,
  a.ANV_HOPS AS HOPS_1,
  b.ANV_PARENT_ID AS P_ID_2,
  b.ANV_PARENT_NAME AS P_NAME_2,
  b.ANV_PARENT_DESC AS P_DESC_2,
  b.ANV_CHILD_ID AS C_ID_2,
  b.ANV_CHILD_NAME AS C_NAME_2,
  b.ANV_CHILD_DESC AS C_DESC_2,
  b.ANV_HOPS AS HOPS_2
FROM AME_RELATION a
JOIN AME_RELATION b ON a.ANV_CHILD_ID = b.ANV_PARENT_ID
WHERE a.ANV_HOPS = 0 AND b.ANV_HOPS = 0

SELECT
  a.ANV_PARENT_ID AS P_ID_1,
  a.ANV_PARENT_NAME AS P_NAME_1,
  a.ANV_PARENT_DESC AS P_DESC_1,
  b.ANV_PARENT_ID AS P_ID_2,
  b.ANV_PARENT_NAME AS P_NAME_2,
  b.ANV_PARENT_DESC AS P_DESC_2,
  b.ANV_CHILD_ID AS C_ID_2,
  b.ANV_CHILD_NAME AS C_NAME_2,
  b.ANV_CHILD_DESC AS C_DESC_2
FROM AME_RELATION a
JOIN AME_RELATION b ON a.ANV_CHILD_ID = b.ANV_PARENT_ID
WHERE a.ANV_HOPS = 0 AND b.ANV_HOPS = 0
AND a.ANV_PARENT_DESC = 'mouse'


SELECT
  a.ANV_PARENT_ID AS AME_ID_1,
  a.ANV_PARENT_NAME AS AME_NAME_1,
  a.ANV_PARENT_DESC AS AME_DESC_1,
  b.ANV_OID AS AME_OID_2,
  b.ANV_PARENT_ID AS AME_ID_2,
  b.ANV_PARENT_NAME AS AME_NAME_2,
  b.ANV_PARENT_DESC AS AME_DESC_2,
  b.ANV_CHILD_ID AS AME_ID_3,
  b.ANV_CHILD_NAME AS AME_NAME_3,
  b.ANV_CHILD_DESC AS AME_DESC_3
FROM AME_RELATION a
JOIN AME_RELATION b ON a.ANV_CHILD_ID = b.ANV_PARENT_ID
WHERE a.ANV_HOPS = 0 AND b.ANV_HOPS = 0
AND a.ANV_PARENT_DESC = 'mouse'
order by b.ANV_OID


SELECT b.ANO_OID AS AME_OID_1, b.ANO_PUBLIC_ID AS AME_NAME_1, b.ANO_COMPONENT_NAME AS AME_DESC_1, a.ANO_OID AS AME_OID_2, a.ANO_PUBLIC_ID AS AME_NAME_2, a.ANO_COMPONENT_NAME AS AME_DESC_2
FROM ANA_RELATIONSHIP
JOIN ANA_NODE AS a ON REL_CHILD_FK = a.ANO_OID
JOIN ANA_NODE AS b ON REL_PARENT_FK = b.ANO_OID
WHERE REL_CHILD_FK NOT IN (SELECT REL_PARENT_FK FROM ANA_RELATIONSHIP)
AND b.ANO_COMPONENT_NAME = 'mouse'

