SELECT 
  CAST(AME_OID_1 AS CHAR) AS ROOT_OID, 
  AME_NAME_1 AS ROOT_NAME, 
  AME_DESC_1 AS ROOT_DESC, 
  b.AME_STAGE_MIN AS ROOT_MIN_STAGE,
  b.AME_STAGE_MAX AS ROOT_MAX_STAGE, 
  CAST(AME_OID_2 AS CHAR) AS CHILD_OID, 
  'LEAF' AS CHILD_ID, 
  AME_NAME_2 AS CHILD_NAME, 
  AME_DESC_2 AS CHILD_DESC, 
  c.AME_STAGE_MIN AS CHILD_MIN_STAGE,
  c.AME_STAGE_MIN AS CHILD_MAX_STAGE, 
  'No Children' AS GRAND_CHILD_ID, 
  'No Children' AS GRAND_CHILD_NAME, 
  'No Children' AS GRAND_CHILD_DESC,
  'No Children' AS GRAND_CHILD_MIN_STAGE,
  'No Children' AS GRAND_CHILD_MAX_STAGE
FROM ANAM_LEAF_RELATION a
JOIN ANAM_STAGE_RANGE b ON AME_OID_1 = b.AME_NODE_FK
JOIN ANAM_STAGE_RANGE c ON AME_OID_2 = c.AME_NODE_FK 
WHERE AME_DESC_1 = 'mouse'

CREATE TABLE ANAM_LEAF_RELATION AS
SELECT
  b.ANO_OID as AME_OID_1,
  b.ANO_PUBLIC_ID as AME_NAME_1, 
  b.ANO_COMPONENT_NAME as AME_DESC_1, 
  c.AME_STAGE_MIN AS AME_ROOT_MIN_STAGE,
  c.AME_STAGE_MAX AS AME_ROOT_MAX_STAGE, 
  a.ANO_OID as AME_OID_2, 
  a.ANO_PUBLIC_ID as AME_NAME_2, 
  a.ANO_COMPONENT_NAME as AME_DESC_2,
  d.AME_STAGE_MIN AS AME_CHILD_MIN_STAGE,
  d.AME_STAGE_MAX AS AME_CHILD_MAX_STAGE
FROM ANA_RELATIONSHIP
JOIN ANA_NODE AS a ON REL_CHILD_FK = a.ANO_OID
JOIN ANA_NODE AS b ON REL_PARENT_FK = b.ANO_OID
JOIN ANAM_STAGE_RANGE c ON b.ANO_OID  = c.AME_NODE_FK
JOIN ANAM_STAGE_RANGE d ON a.ANO_OID = d.AME_NODE_FK 
WHERE REL_CHILD_FK NOT IN (SELECT REL_PARENT_FK FROM ANA_RELATIONSHIP)
ORDER BY b.ANO_PUBLIC_ID, b.ANO_COMPONENT_NAME;