SELECT ANO_PUBLIC_ID, A.STG_NAME AS START, B.STG_NAME AS STOP
FROM ANAV_STAGE_RANGE
JOIN ANA_STAGE A ON A.STG_SEQUENCE = ANAV_STAGE_MIN
JOIN ANA_STAGE B ON B.STG_SEQUENCE = ANAV_STAGE_MAX
JOIN ANA_NODE ON ANO_OID = ANAV_NODE_FK


SELECT a.ANO_COMPONENT_NAME AS Child, b.ANO_COMPONENT_NAME AS Parent, e.hops AS Hops 
FROM edge e
JOIN ANA_NODE AS a ON e.child_node = a.ANO_OID
JOIN ANA_NODE AS b ON e.parent_node = b.ANO_OID
WHERE e.child_node = '30141'

SELECT
  e.oid AS ANV_OID, 
  e.entry_edge_id AS ANV_ENTRY_EDGE_ID, 
  e.direct_edge_id AS ANV_DIRECT_EDGE_ID, 
  e.exit_edge_id AS ANV_EXIT_EDGE_ID, 
  e.child_node AS ANV_CHILD_ID, 
  a.ANO_COMPONENT_NAME AS ANV_CHILD_NAME, 
  e.parent_node AS ANV_PARENT_ID,
  b.ANO_COMPONENT_NAME AS ANV_PARENT_NAME,
  e.hops AS ANV_HOPS,
  e.source AS ANV_SOURCE
FROM edge e
JOIN ANA_NODE AS a ON e.child_node = a.ANO_OID
JOIN ANA_NODE AS b ON e.parent_node = b.ANO_OID
WHERE e.child_node = '30141'

--List Ancestors By Child ID
SELECT
  ANV_OID, 
  ANV_ENTRY_EDGE_ID, 
  ANV_DIRECT_EDGE_ID, 
  ANV_EXIT_EDGE_ID, 
  ANV_CHILD_ID, 
  ANV_CHILD_NAME, 
  ANV_PARENT_ID,
  ANV_PARENT_NAME,
  ANV_HOPS,
  ANV_SOURCE
FROM ANAV_RELATION
WHERE ANV_CHILD_ID = '30141'
ORDER BY ANV_HOPS DESC

--List Ancestors By Child Name
SELECT
  ANV_OID, 
  ANV_ENTRY_EDGE_ID, 
  ANV_DIRECT_EDGE_ID, 
  ANV_EXIT_EDGE_ID, 
  ANV_CHILD_ID, 
  ANV_CHILD_NAME, 
  ANV_PARENT_ID,
  ANV_PARENT_NAME,
  ANV_HOPS,
  ANV_SOURCE
FROM ANAV_RELATION
WHERE ANV_CHILD_DESC = 'prostatic urethra'
ORDER BY ANV_HOPS DESC

--List  Immediate Descendants By Parent Name
SELECT
  ANV_OID, 
  ANV_ENTRY_EDGE_ID, 
  ANV_DIRECT_EDGE_ID, 
  ANV_EXIT_EDGE_ID, 
  ANV_CHILD_ID, 
  ANV_CHILD_NAME, 
  ANV_PARENT_ID,
  ANV_PARENT_NAME,
  ANV_HOPS,
  ANV_SOURCE
FROM ANAV_RELATION
WHERE ANV_PARENT_DESC = 'mouse'
AND ANV_HOPS = 0
ORDER BY ANV_HOPS DESC

--List Immediate Descendants By Parent Id
SELECT
  ANV_OID, 
  ANV_ENTRY_EDGE_ID, 
  ANV_DIRECT_EDGE_ID, 
  ANV_EXIT_EDGE_ID, 
  ANV_CHILD_ID, 
  ANV_CHILD_NAME, 
  ANV_PARENT_ID,
  ANV_PARENT_NAME,
  ANV_HOPS,
  ANV_SOURCE
FROM ANAV_RELATION
WHERE ANV_PARENT_ID = '33'
AND ANV_HOPS = 0
ORDER BY ANV_HOPS DESC

--List Immediate Descendants By Parent Name
SELECT
  ANV_OID, 
  ANV_ENTRY_EDGE_ID, 
  ANV_DIRECT_EDGE_ID, 
  ANV_EXIT_EDGE_ID, 
  ANV_CHILD_ID, 
  ANV_CHILD_NAME, 
  ANV_PARENT_ID,
  ANV_PARENT_NAME,
  ANV_HOPS,
  ANV_SOURCE
FROM ANAV_RELATION
WHERE ANV_PARENT_NAME = 'vertebral axis muscle system'
AND ANV_HOPS = 0
ORDER BY ANV_HOPS DESC

SELECT
  ANV_OID, 
  ANV_ENTRY_EDGE_ID, 
  ANV_DIRECT_EDGE_ID, 
  ANV_EXIT_EDGE_ID, 
  ANV_CHILD_ID, 
  ANV_CHILD_NAME, 
  ANV_PARENT_ID,
  ANV_PARENT_NAME,
  ANV_HOPS,
  ANV_SOURCE
FROM ANAV_RELATION
WHERE ANV_PARENT_ID = '26087'
AND ANV_HOPS = 0
ORDER BY ANV_HOPS DESC

