-- Create ANA_NODE_PERSPECTIVE_LINK
-- 1. The 'Adult Kidney (GenePaint)' Perspective
-- Children of START Nodes
--  EXCLUDING STOP Nodes and their children
SELECT CONCAT("INSERT INTO ANA_NODE_PERSPECTIVE_LINK (NPL_PERSPECTIVE_FK, NPL_NODE_FK) VALUES (", "\'Adult Kidney (GenePaint)\'", ",", AME_CHILD_NODE, ");") AS "-- INSERT INTO ANA_NODE_PERSPECTIVE_LINK"
FROM ANAM_EDGE
WHERE AME_PARENT_NODE IN (31638, 31627, 31639, 30107, 30106, 13125, 13133, 28804)
AND AME_CHILD_NODE NOT IN (SELECT
AME_PARENT_NODE
FROM ANAM_EDGE
WHERE AME_PARENT_NODE IN (27026, 26993, 27055, 30296, 31712, 27017))
UNION
-- START Nodes as well
SELECT CONCAT("INSERT INTO ANA_NODE_PERSPECTIVE_LINK (NPL_PERSPECTIVE_FK, NPL_NODE_FK) VALUES (", "\'", PAM_PERSPECTIVE_FK, "\',", PAM_NODE_FK, ");") AS "-- INSERT INTO ANA_NODE_PERSPECTIVE_LINK"
FROM ANA_PERSPECTIVE_AMBIT
WHERE PAM_PERSPECTIVE_FK = 'Adult Kidney (GenePaint)'
AND PAM_IS_START = 1
UNION
-- 2. The 'Urogenital' Perspective
-- Children of START Nodes
SELECT CONCAT("INSERT INTO ANA_NODE_PERSPECTIVE_LINK (NPL_PERSPECTIVE_FK, NPL_NODE_FK) VALUES (", "\'Urogenital\'", ",", AME_CHILD_NODE, ");") AS "-- INSERT INTO ANA_NODE_PERSPECTIVE_LINK"
FROM ANAM_EDGE
WHERE AME_PARENT_NODE IN (11673, 26962, 13306, 10381)
UNION
-- START Nodes as well
SELECT CONCAT("INSERT INTO ANA_NODE_PERSPECTIVE_LINK (NPL_PERSPECTIVE_FK, NPL_NODE_FK) VALUES (", "\'", PAM_PERSPECTIVE_FK, "\',", PAM_NODE_FK, ");") AS "-- INSERT INTO ANA_NODE_PERSPECTIVE_LINK"
FROM ANA_PERSPECTIVE_AMBIT
WHERE PAM_PERSPECTIVE_FK = 'Urogenital'
AND PAM_IS_START = 1
UNION
-- 3. The 'Renal' Perspective
-- Children of START Nodes
SELECT CONCAT("INSERT INTO ANA_NODE_PERSPECTIVE_LINK (NPL_PERSPECTIVE_FK, NPL_NODE_FK) VALUES (", "\'Renal\'", ",", AME_CHILD_NODE, ");") AS "-- INSERT INTO ANA_NODE_PERSPECTIVE_LINK"
FROM ANAM_EDGE
WHERE AME_PARENT_NODE IN (11673, 26962, 10381)
UNION
-- START Nodes as well
SELECT CONCAT("INSERT INTO ANA_NODE_PERSPECTIVE_LINK (NPL_PERSPECTIVE_FK, NPL_NODE_FK) VALUES (", "\'", PAM_PERSPECTIVE_FK, "\',", PAM_NODE_FK, ");") AS "-- INSERT INTO ANA_NODE_PERSPECTIVE_LINK"
FROM ANA_PERSPECTIVE_AMBIT
WHERE PAM_PERSPECTIVE_FK = 'Renal'
AND PAM_IS_START = 1
UNION
-- 4. The 'Whole mouse' Perspective
-- Children of START Nodes
SELECT CONCAT("INSERT INTO ANA_NODE_PERSPECTIVE_LINK (NPL_PERSPECTIVE_FK, NPL_NODE_FK) VALUES (", "\'Whole mouse\'", ",", AME_CHILD_NODE, ");") AS "-- INSERT INTO ANA_NODE_PERSPECTIVE_LINK"
FROM ANAM_EDGE
WHERE AME_PARENT_NODE IN (33)
UNION
-- START Nodes as well
SELECT CONCAT("INSERT INTO ANA_NODE_PERSPECTIVE_LINK (NPL_PERSPECTIVE_FK, NPL_NODE_FK) VALUES (", "\'", PAM_PERSPECTIVE_FK, "\',", PAM_NODE_FK, ");") AS "-- INSERT INTO ANA_NODE_PERSPECTIVE_LINK"
FROM ANA_PERSPECTIVE_AMBIT
WHERE PAM_PERSPECTIVE_FK = 'Whole mouse'
AND PAM_IS_START = 1;
