SELECT CONCAT("UPDATE ANA_OBJECT SET OBJ_TABLE = \"ANA_VERSION\", OBJ_DESCRIPTION = \"VERSION00", VER_NUMBER, "\", OBJ_CREATION_DATETIME = \"", VER_DATE, "\", OBJ_CREATOR_FK = 2 WHERE OBJ_OID = ", VER_OID, ";")
AS '-- VERSION_STRING'
FROM ANA_VERSION;