INSERT INTO ANA_RELATIONSHIP_PROJECT 
(RLP_RELATIONSHIP_FK, RLP_SEQUENCE, RLP_PROJECT_FK)
SELECT REL_OID, NULL, 'EMAP'
FROM ANA_RELATIONSHIP
WHERE REL_OID NOT IN (SELECT RLP_RELATIONSHIP_FK FROM ANA_RELATIONSHIP_PROJECT WHERE RLP_PROJECT_FK = 'EMAP')
