DROP TABLE IF EXISTS ANA_OBO_USER;
CREATE TABLE ANA_OBO_USER (
  AOU_OID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  AOU_NAME varchar(255) NOT NULL,
  AOU_PASSWORD varchar(255) NOT NULL,
  AOU_EMAIL varchar(255) NOT NULL,
  AOU_ORGANISATION varchar(255) DEFAULT NULL,
  PRIMARY KEY (AOU_OID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
