DROP TABLE IF EXISTS ANA_OBO_COMPONENT_RELATIONSHIP;
CREATE TABLE ANA_OBO_COMPONENT_RELATIONSHIP (
    ACR_OID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ACR_OBO_ID VARCHAR(25) NOT NULL,
    ACR_OBO_TYPE VARCHAR(25) NOT NULL,
    ACR_OBO_PARENT VARCHAR(25) NOT NULL,
    PRIMARY KEY (ACR_OID),
    INDEX ACR_IDX1 (ACR_OBO_ID),
    INDEX ACR_IDX2 (ACR_OBO_PARENT)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
