DROP TABLE IF EXISTS ANA_OBO_COMPONENT_SYNONYM;
CREATE TABLE ANA_OBO_COMPONENT_SYNONYM (
    ACS_OID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ACS_OBO_ID VARCHAR(25) NOT NULL,
    ACS_OBO_TEXT VARCHAR(1000) NOT NULL,
    INDEX ACS_IDX1 (ACS_OBO_ID),
    PRIMARY KEY (ACS_OID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
