DROP TABLE IF EXISTS ANA_OBO_FILE;
CREATE TABLE ANA_OBO_FILE (
  AOF_OID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  AOF_FILE_NAME varchar(255) NOT NULL,
  AOF_FILE_CONTENT mediumblob,
  AOF_FILE_CONTENT_TYPE varchar(255) NOT NULL,
  AOF_FILE_CONTENT_LENGTH int(10) DEFAULT NULL,
  AOF_FILE_CONTENT_DATE datetime DEFAULT NULL,
  AOF_FILE_VALIDATION varchar(20) DEFAULT NULL COMMENT 'NEW/VALIDATED/FAILED',
  AOF_FILE_AUTHOR varchar(20) DEFAULT NULL,
  AOF_TEXT_REPORT_NAME varchar(255) DEFAULT NULL,
  AOF_TEXT_REPORT mediumblob,
  AOF_TEXT_REPORT_TYPE varchar(255) DEFAULT NULL,
  AOF_TEXT_REPORT_LENGTH int(10) DEFAULT NULL,
  AOF_TEXT_REPORT_DATE datetime DEFAULT NULL,
  AOF_PDF_REPORT_NAME varchar(255) DEFAULT NULL,
  AOF_PDF_REPORT mediumblob,
  AOF_PDF_REPORT_TYPE varchar(255) DEFAULT NULL,
  AOF_PDF_REPORT_LENGTH int(10) DEFAULT NULL,
  AOF_PDF_REPORT_DATE datetime DEFAULT NULL,
  PRIMARY KEY (AOF_OID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
